# Generated by Django 4.2 on 2023-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
