# Generated by Django 4.2 on 2023-04-20 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organisation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='nibss_code',
        ),
        migrations.AddField(
            model_name='organisation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
