# Generated by Django 2.2 on 2023-05-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230506_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='support_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
