# Generated by Django 2.2 on 2023-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_organisation_support_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='support_email',
        ),
        migrations.AddField(
            model_name='organisation',
            name='support_emails',
            field=models.TextField(null=True),
        ),
    ]
