# Generated by Django 2.2 on 2023-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='metrics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
