# Generated by Django 2.2 on 2023-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230517_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(null=True, upload_to='site-logos'),
        ),
    ]
