# Generated by Django 2.2 on 2023-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_organisation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='site-logos')),
            ],
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='logo',
        ),
    ]
