# Generated by Django 2.2 on 2023-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_organisation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='metrics',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
