# Generated by Django 2.2 on 2023-06-30 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0016_emailtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
