# Generated by Django 4.2 on 2023-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=15)),
                ('count', models.IntegerField()),
                ('requesttime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('institution', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('payarena', models.CharField(max_length=6)),
                ('payattitude', models.CharField(max_length=6)),
                ('nip', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'bins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('code', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('nibss_code', models.CharField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('routes', models.TextField(blank=True, null=True)),
                ('supports_ir', models.BooleanField(blank=True, null=True)),
                ('health_interval', models.IntegerField(blank=True, null=True)),
                ('config', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
                ('ir_intervals', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=15)),
                ('txid', models.CharField(blank=True, max_length=150, null=True)),
                ('direction', models.CharField(blank=True, max_length=5, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=75, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('rawmsg', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('occurred', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=15, null=True)),
                ('txid', models.CharField(blank=True, max_length=150, null=True)),
                ('sourcebank', models.CharField(blank=True, max_length=15, null=True)),
                ('destbank', models.CharField(blank=True, max_length=15, null=True)),
                ('accountno', models.CharField(blank=True, max_length=20, null=True)),
                ('poolaccount', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('remark', models.CharField(blank=True, max_length=2000, null=True)),
                ('requestid', models.CharField(blank=True, max_length=150, null=True)),
                ('requesttype', models.CharField(blank=True, max_length=50, null=True)),
                ('requesttime', models.DateTimeField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=50, null=True)),
                ('routebin', models.CharField(blank=True, max_length=10, null=True)),
                ('responsetime', models.DateTimeField(blank=True, null=True)),
                ('statuscode', models.CharField(blank=True, max_length=20, null=True)),
                ('statusmessage', models.CharField(blank=True, max_length=200, null=True)),
                ('responseid', models.CharField(blank=True, max_length=150, null=True)),
                ('rrn', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.CharField(blank=True, max_length=20, null=True)),
                ('requerycount', models.SmallIntegerField(blank=True, null=True)),
                ('reversed', models.BooleanField(blank=True, null=True)),
                ('reversible', models.BooleanField(blank=True, null=True)),
                ('batchid', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=60, null=True)),
                ('sender', models.CharField(blank=True, max_length=60, null=True)),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
                ('debitaccount', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('institution', models.CharField(max_length=15)),
                ('txid', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('sourcebank', models.CharField(max_length=15)),
                ('destbank', models.CharField(max_length=15)),
                ('accountno', models.CharField(max_length=20)),
                ('poolaccount', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('fee', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('remark', models.CharField(blank=True, max_length=2000, null=True)),
                ('requestid', models.CharField(blank=True, max_length=150, null=True)),
                ('requesttype', models.CharField(blank=True, max_length=50, null=True)),
                ('requesttime', models.DateTimeField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=50, null=True)),
                ('routebin', models.CharField(blank=True, max_length=10, null=True)),
                ('responsetime', models.DateTimeField(blank=True, null=True)),
                ('statuscode', models.CharField(blank=True, max_length=20, null=True)),
                ('statusmessage', models.CharField(blank=True, max_length=200, null=True)),
                ('responseid', models.CharField(blank=True, max_length=150, null=True)),
                ('rrn', models.CharField(blank=True, max_length=150, null=True)),
                ('client', models.CharField(blank=True, max_length=20, null=True)),
                ('requerycount', models.SmallIntegerField(blank=True, null=True)),
                ('reversed', models.BooleanField(blank=True, null=True)),
                ('reversible', models.BooleanField(blank=True, null=True)),
                ('batchid', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=200, null=True)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(max_length=10)),
                ('debitaccount', models.CharField(blank=True, max_length=15, null=True)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
    ]
